# Texto original
texto_original = """
(1, '25 mph', 1), 
(1, '35 mph', 0),
(1, '40 mph', 0),
(1, '50 mph', 0),
(2, 'Solo en carreteras', 0),
(2, 'Siempre que el vehículo esté en movimiento', 1),  
(2, 'Solo cuando hay policías cerca', 0),
(2, 'Solo en viajes largos', 0),
(3, 'Llamar al 911 inmediatamente', 0),
(3, 'Mover el vehículo fuera del tráfico si es seguro hacerlo', 1),  
(3, 'Abandonar la escena para evitar retrasos', 0),
(3, 'Seguir conduciendo si el vehículo aún funciona', 0),
(4, '0.02%', 0),
(4, '0.05%', 0),
(4, '0.08%', 1),
(4, '0.10%', 0),
(5, 'Se permite adelantar en cualquier momento', 0),
(5, 'No se permite adelantar en ninguna dirección', 1),
(5, 'Solo los vehículos comerciales pueden adelantar', 0),
(5, 'Se puede adelantar con precaución', 0),
(6, 'Solo de noche', 0),
(6, 'Cuando hay niebla, lluvia o nieve', 1), 
(6, 'En cualquier momento del día', 0),
(6, 'Solo en autopistas', 0),
(7, 'Proceder con precaución sin detenerse', 0),
(7, 'Detenerse y continuar solo cuando sea seguro', 1),
(7, 'Girar a la derecha sin detenerse', 0),
(7, 'Acelerar antes de que cambie la luz', 0),
(8, '1 pie', 0),
(8, '2 pies', 0),
(8, '3 pies', 1),
(8, '5 pies', 0),
(9, 'Para adelantar otro vehículo', 0),
(9, 'Para entrar a una propiedad privada', 1),
(9, 'En una intersección', 0),
(9, 'Nunca', 0),
(10, 'Siempre que no haya tráfico', 0),
(10, 'Solo en intersecciones con señales permitiéndolo', 1),
(10, 'Nunca', 0),
(10, 'A cualquier hora del día', 0),
(11, 'Girar el volante en la dirección opuesta', 0),
(11, 'Frenar inmediatamente', 0),
(11, 'Soltar el acelerador y girar en la dirección del derrape', 1),
(11, 'Acelerar para recuperar el control', 0),
(12, 'Cuando haya una línea amarilla continua', 0),
(12, 'Cuando haya una línea amarilla discontinua en tu lado', 1),
(12, 'En cualquier momento', 0),
(12, 'Nunca', 0),
(13, 'Acelerar para cruzar rápidamente', 0),
(13, 'Detenerte completamente y verificar si viene un tren', 1),
(13, 'Tocar la bocina antes de cruzar', 0),
(13, 'Reducir la velocidad y proceder con precaución', 0),
(14, 'Nunca es ilegal', 0),
(14, 'Cuando hay niebla', 0),
(14, 'Cuando hay otros vehículos cerca', 1),
(14, 'Solo en autopistas', 0),
(15, 'Acelerar hasta alcanzar la velocidad del tráfico', 1),
(15, 'Detenerse antes de entrar', 0),
(15, 'Entrar lentamente y luego acelerar', 0),
(15, 'Encender las luces intermitentes y avanzar sin detenerse', 0),
(16, 'Mientras conduces en una carretera con tráfico denso', 0),
(16, 'Solo cuando tu vehículo está detenido por una emergencia', 1),
(16, 'Siempre que frenes de manera repentina', 0),
(16, 'Al conducir de noche', 0),
(17, 'Detenerte inmediatamente en el carril de tráfico', 0),
(17, 'Tratar de llegar al arcén o un lugar seguro', 1),
(17, 'Pedir ayuda a otros conductores', 0),
(17, 'Salir del vehículo y caminar hasta la salida más cercana', 0),
(18, 'Puedes girar en la dirección de la flecha sin detenerte', 0),
(18, 'Tienes el derecho de paso para girar, pero debes ceder a peatones y tráfico', 1),
(18, 'Debes detenerte antes de girar', 0),
(18, 'Solo se aplica a vehículos comerciales', 0),
(19, 'Estacionamiento permitido solo para residentes', 0),
(19, 'No se permite detenerse, estacionarse o esperar', 1),
(19, 'Estacionamiento permitido solo de noche', 0),
(19, 'Espacio reservado para vehículos eléctricos', 0),
(20, 'Usar luces altas', 0),
(20, 'Encender las luces bajas y reducir la velocidad', 1),
(20, 'Detenerte en la carretera y esperar a que la niebla pase', 0),
(20, 'Usar luces intermitentes todo el tiempo', 0),
(21, 'Acelerar para cruzar rápidamente', 0),
(21, 'Ceder el paso a los vehículos que llegaron primero', 1),
(21, 'Tocar la bocina y avanzar', 0),
(21, 'Girar a la derecha sin detenerte', 0),
(22, 'Mantener una distancia segura con el vehículo adelante', 1),
(22, 'Frenar bruscamente cuando sea necesario', 0),
(22, 'Conducir más rápido para evitar que otros te alcancen', 0),
(22, 'Usar luces intermitentes en todo momento', 0),
(23, 'Solo de noche', 0),
(23, 'En túneles, lluvia y niebla', 1),
(23, 'Solo en autopistas', 0),
(23, 'Nunca, solo se usan las luces altas', 0),
(24, 'Detenerte completamente', 0),
(24, 'Reducir la velocidad y ceder el paso si es necesario', 1),
(24, 'Ignorar la señal y seguir adelante', 0),
(24, 'Acelerar para evitar detenerte', 0),
(25, 'Para adelantar a un vehículo lento', 0),
(25, 'Para girar a la izquierda hacia un estacionamiento o entrada privada', 1),
(25, 'En cualquier momento si no hay tráfico', 0),
(25, 'Nunca', 0),
(26, 'Acercarte lo más posible al borde derecho y girar con precaución', 1),
(26, 'Girar desde cualquier carril disponible', 0),
(26, 'No usar señales de giro', 0),
(26, 'Girar lentamente sin revisar los espejos', 0),
(27, 'En cualquier calle pública', 0),
(27, 'Cuando bloqueas el tráfico', 0),
(27, 'En carreteras y autopistas', 1),
(27, 'Siempre es legal si es seguro', 0),
(28, 'Detenerte completamente', 0),
(28, 'Proceder con precaución cediendo el paso al tráfico y peatones', 1),
(28, 'Acelerar antes de que la luz cambie a roja', 0),
(28, 'Ignorarla y avanzar normalmente', 0),
(29, 'Una advertencia verbal', 0),
(29, 'Multa de hasta $1,000 y posible suspensión de la licencia', 1),
(29, 'Ninguna sanción si no hay niños cruzando', 0),
(29, 'Solo una reducción de puntos en la licencia', 0),
(30, 'Solo en emergencias para evitar un accidente', 1),
(30, 'Para saludar a otros conductores', 0),
(30, 'Siempre que cambies de carril', 0),
(30, 'En intersecciones para alertar a peatones', 0),
(31, 'Separación de carriles en la misma dirección donde se permite cambiar', 1),
(31, 'Prohibición total de adelantar', 0),
(31, 'Separación de carriles en sentido contrario', 0),
(31, 'Solo vehículos comerciales pueden cruzarla', 0),
(32, 'Acelerar para recuperar el control', 0),
(32, 'Soltar el acelerador y mantener el volante recto', 1),
(32, 'Girar bruscamente el volante', 0),
(32, 'Frenar de inmediato', 0),
(33, 'Acelerar para evitar ser detenido', 0),
(33, 'Encender tus intermitentes y detenerte en un lugar seguro', 1),
(33, 'Ignorarlo y seguir conduciendo', 0),
(33, 'Cambiar de carril sin detenerte', 0),
(34, 'Solo una advertencia verbal', 0),
(34, 'Multa, suspensión de la licencia y posible cárcel', 1),
(34, 'Pérdida de puntos sin multa', 0),
(34, 'No hay sanción si es la primera vez', 0),
(35, 'Siempre que no haya tráfico en sentido contrario', 0),
(35, 'Cuando la línea en tu lado es discontinua y es seguro hacerlo', 1),
(35, 'Nunca', 0),
(35, 'En curvas sin visibilidad', 0),
(36, 'Frenar solo si el peatón está en tu carril', 0),
(36, 'Ceder el paso y detenerte si es necesario', 1),
(36, 'Usar la bocina para que se apure', 0),
(36, 'Pasar antes de que llegue al otro lado', 0),
(37, 'Tomar descansos frecuentes', 1),
(37, 'Beber café y seguir conduciendo', 0),
(37, 'Manejar con la ventana abierta', 0),
(37, 'Conducir más rápido para llegar antes', 0),
(38, 'Carretera cerrada a vehículos grandes', 0),
(38, 'Descenso peligroso, reduce la velocidad y usa frenos con precaución', 1),
(38, 'Solo camiones pueden usar ese carril', 0),
(38, 'Zona de velocidad mínima', 0),
(39, 'Nunca', 1),
(39, 'Solo por menos de 5 minutos', 0),
(39, 'Si no hay peatones presentes', 0),
(39, 'Solo de noche', 0),
(40, '1 segundo', 0),
(40, '2 segundos', 0),
(40, '3 segundos o más', 1),
(40, '5 segundos exactos', 0),
(41, 'Acelerar para despejar el camino', 0),
(41, 'Detenerte inmediatamente en el carril', 0),
(41, 'Moverte hacia la derecha y detenerte si es seguro', 1),
(41, 'Ignorarlo si no está en tu carril', 0),
(42, 'Siempre', 0),
(42, 'Solo después de detenerse completamente y ceder el paso', 1),
(42, 'Nunca', 0),
(42, 'Solo si hay un carril exclusivo para giros', 0),
(43, 'Advertencia verbal', 0),
(43, 'Multa y posible reducción de puntos en la licencia', 1),
(43, 'No hay sanción', 0),
(43, 'Solo una advertencia si es la primera vez', 0),
(44, 'Abandonar la escena si tu auto aún funciona', 0),
(44, 'Mover el vehículo fuera del tráfico si es seguro y contactar a las autoridades', 1),
(44, 'Dejar el auto en la vía sin moverte', 0),
(44, 'Continuar conduciendo y reportarlo más tarde', 0),
(45, 'No se permite cambiar de carril', 1),
(45, 'Se permite adelantar a cualquier velocidad', 0),
(45, 'Puedes cambiar de carril sin restricciones', 0),
(45, 'Indica un carril exclusivo para giros', 0),
(46, 'Alto', 1),
(46, 'Ceda el paso', 0),
(46, 'Precaución', 0),
(46, 'Cruce de ferrocarril', 0),
(47, 'Acelerar para evitar golpear un animal', 0),
(47, 'Reducir la velocidad y estar atento a posibles animales en la vía', 1),
(47, 'Ignorar la señal si no ves animales', 0),
(47, 'Sonar la bocina para ahuyentar a los animales', 0),
(48, 'Solo de noche', 0),
(48, 'Cuando hay poca visibilidad por condiciones climáticas', 1),
(48, 'Solo en autopistas', 0),
(48, 'Nunca es obligatorio', 0),
(49, 'Abandonarlo de inmediato', 0),
(49, 'Encender las luces de emergencia y tratar de salir de la vía', 1),
(49, 'Dejarlo en medio del carril y buscar ayuda', 0),
(49, 'Seguir conduciendo hasta encontrar un mecánico', 0),
(50, 'Adelantar a otro vehículo en el cruce', 1),
(50, 'Detenerse antes de cruzar si se acercan trenes', 0),
(50, 'Mirar a ambos lados antes de cruzar', 0),
(50, 'Reducir la velocidad antes de llegar al cruce', 0),
(51, 'Frenar completamente antes de incorporarte', 0),
(51, 'Acelerar hasta alcanzar la velocidad del tráfico y unirte con seguridad', 1),
(51, 'Ingresar lentamente sin verificar el tráfico', 0),
(51, 'Detenerte y esperar a que alguien te ceda el paso', 0),
(52, 'Siempre que veas una señal de cruce', 0),
(52, 'Solo si las barreras están bajadas o las luces intermitentes están activas', 1),
(52, 'Nunca es obligatorio detenerse', 0),
(52, 'Solo si hay tráfico intenso', 0),
(53, 'Giro obligatorio', 0),
(53, 'Curva pronunciada más adelante', 1),
(53, 'Fin de la carretera', 0),
(53, 'Zona de reducción de velocidad', 0),
(54, 'Usar luces bajas y reducir la velocidad', 1),
(54, 'Encender luces altas para ver mejor', 0),
(54, 'Acelerar para salir rápido de la niebla', 0),
(54, 'Detenerte en medio de la carretera', 0),
(55, 'Advertencia verbal', 0),
(55, 'Multa y posible reducción de puntos en la licencia', 1),
(55, 'No hay sanción si no hay tráfico', 0),
(55, 'Solo una advertencia si es la primera vez', 0),
(56, 'Frenar de inmediato con fuerza', 0),
(56, 'Reducir la velocidad y tratar de esquivar con precaución', 1),
(56, 'Acelerar para evitar el impacto', 0),
(56, 'Tocar la bocina y seguir conduciendo', 0),
(57, 'Estacionamiento prohibido en todo momento', 0),
(57, 'Solo se permite cargar y descargar pasajeros o mercancía por un tiempo limitado', 1),
(57, 'Estacionamiento exclusivo para residentes', 0),
(57, 'Espacio reservado para vehículos eléctricos', 0),
(58, 'Apagar el motor inmediatamente', 0),
(58, 'Bajar a una marcha más baja y usar el freno de emergencia', 1),
(58, 'Saltar del vehículo en movimiento', 0),
(58, 'Seguir conduciendo hasta que el vehículo se detenga solo', 0),
(59, 'Solo si tienes el número mínimo de pasajeros requerido', 1),
(59, 'Siempre, sin importar el número de pasajeros', 0),
(59, 'Solo si es hora pico', 0),
(59, 'Solo si tu vehículo es eléctrico', 0),
(60, 'Acelerar para pasar rápidamente', 0),
(60, 'Reducir la velocidad y estar preparado para vehículos grandes que reduzcan su velocidad', 1),
(60, 'No hacer nada, ya que solo aplica a camiones', 0),
(60, 'Detenerte completamente', 0),
(61, 'Acelerar para cruzar antes de que cambie a rojo', 0),
(61, 'Reducir la velocidad y detenerte si es seguro hacerlo', 1),
(61, 'Ignorar la luz y continuar a velocidad normal', 0),
(61, 'Detenerte inmediatamente sin importar la distancia', 0),
(62, 'Reducir la velocidad bruscamente antes de entrar a la rampa de salida', 0),
(62, 'Señalizar con anticipación y reducir la velocidad dentro del carril de desaceleración', 1),
(62, 'Girar rápidamente en la salida sin señalizar', 0),
(62, 'Salir en reversa si pasaste la salida', 0),
(63, 'Detenerte y ceder el paso al peatón', 1),
(63, 'Sonar la bocina para que se apure', 0),
(63, 'Ignorarlo y seguir conduciendo', 0),
(63, 'Acelerar antes de que el peatón llegue a tu carril', 0),
(64, 'No hay sanción', 0),
(64, 'Multa y posible suspensión de la licencia', 1),
(64, 'Solo una advertencia verbal', 0),
(64, 'Arresto inmediato', 0),
(65, 'Cuando ves ambos faros del vehículo adelantado en tu espejo retrovisor', 1),
(65, 'Inmediatamente después de adelantar', 0),
(65, 'Cuando el otro conductor toca la bocina', 0),
(65, 'Después de cinco segundos, sin importar la distancia', 0),
(66, 'Área de caza permitida', 0),
(66, 'Posible cruce de animales, reducir la velocidad y estar alerta', 1),
(66, 'Solo decorativa, no es importante', 0),
(66, 'Prohibido conducir de noche', 0),
(67, 'Límite del carril, indica el borde de la carretera', 1),
(67, 'Carril exclusivo para adelantar', 0),
(67, 'Prohibido girar a la derecha', 0),
(67, 'Carril exclusivo para bicicletas', 0),
(68, 'Cuando el peatón ya cruzó la mitad de la calle', 0),
(68, 'Nunca, hasta que el peatón haya cruzado completamente', 1),
(68, 'Solo si tocas la bocina primero', 0),
(68, 'Siempre que no haya policías cerca', 0),
(69, '2 segundos', 0),
(69, '3 segundos o más', 1),
(69, 'No hay distancia mínima', 0),
(69, '1 segundo', 0),
(70, 'Sujetar firmemente el volante y reducir la velocidad gradualmente', 1),
(70, 'Frenar inmediatamente', 0),
(70, 'Girar rápidamente el volante', 0),
(70, 'Acelerar para estabilizar el vehículo', 0),
(71, 'Girar bruscamente el volante para regresar a la carretera', 0),
(71, 'Reducir la velocidad gradualmente y regresar con cuidado', 1),
(71, 'Acelerar para reincorporarte rápidamente', 0),
(71, 'Frenar bruscamente para detenerte de inmediato', 0),
(72, 'Solo si no hay una señal que lo prohíba y es seguro hacerlo', 1),
(72, 'Siempre que no haya otros vehículos', 0),
(72, 'Nunca', 0),
(72, 'Solo en carreteras rurales', 0),
(73, 'Girar bruscamente hacia la izquierda', 0),
(73, 'Reducir la velocidad y moverte hacia la derecha', 1),
(73, 'Acelerar para pasar más rápido', 0),
(73, 'Tocar la bocina y continuar derecho', 0),
(74, '55 mph', 0),
(74, '65 mph', 1),
(74, '75 mph', 0),
(74, '85 mph', 0),
(75, 'Ignorar la orden y seguir conduciendo', 0),
(75, 'Detenerte de inmediato en el carril', 0),
(75, 'Encender las luces intermitentes y detenerte en un lugar seguro', 1),
(75, 'Acelerar para evitar una multa', 0),
(76, 'Siempre que tenga luces rojas intermitentes encendidas', 1),
(76, 'Solo en zonas escolares', 0),
(76, 'Solo si hay niños bajando del autobús', 0),
(76, 'Nunca', 0),
(77, 'Alto total, luego continuar cuando sea seguro', 1),
(77, 'Precaución, reducir la velocidad', 0),
(77, 'No tiene ningún significado', 0),
(77, 'Acelerar antes de que cambie a verde', 0),
(78, 'Reduce el tiempo de reacción y afecta el juicio', 1),
(78, 'Mejora la concentración', 0),
(78, 'No afecta la conducción si se consume en pequeñas cantidades', 0),
(78, 'Aumenta la capacidad de respuesta del conductor', 0),
(79, '30 minutos después del atardecer y 30 minutos antes del amanecer', 1),
(79, 'Solo cuando llueve', 0),
(79, 'Solo en carreteras rurales', 0),
(79, 'No es obligatorio', 0),
(80, 'Girar las ruedas hacia el bordillo si es cuesta abajo, y en dirección contraria si es cuesta arriba', 1),
(80, 'Dejar las ruedas rectas', 0),
(80, 'Siempre girar las ruedas hacia la izquierda', 0),
(80, 'No importa la dirección', 0);
"""

# Resultado modificado
resultado = ""
for linea in texto_original.strip().splitlines():
    if not linea.strip():
        continue
    linea = linea.strip().rstrip(',')
    if linea.startswith('('):
        id_original = int(linea.split(',')[0][1:])  # Extrae el primer número entre paréntesis
        if 1 <= id_original <= 80:
            nuevo_id = id_original + 160
            linea_modificada = linea.replace(f"({id_original},", f"({nuevo_id},")
            resultado += linea_modificada + ",\n"
        else:
            resultado += linea + ",\n"

print(resultado)
